name: CI/CD Pipeline for API Tests

on:
  push:
    branches:
      - main  # Trigger when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger when a pull request is made to the main branch

jobs:
  test:
    runs-on: windows-latest  # Use a Windows environment for running the tests

    steps:
      - name: Start CI/CD Pipeline
        run: echo "🚀 CI/CD pipeline started for API tests..."

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Confirm Repository Checkout
        run: echo "✅ Repository checked out successfully!"

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the version of Node.js you want 
      - name: Confirm Node.js Setup
        run: |
          node -v
          echo "✅ Node.js is set up successfully!"

      # Install dependencies
      - name: Install dependencies
        run: |
          "Installing Newman and reporters..."
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          "Dependencies installed successfully!"

      # Run Postman tests using Newman with detailed logs
      - name: Run Postman tests using Newman
        run: |
          "Running API tests..."
           newman run "Practice for CICD.postman_collection.json"
          "API tests completed! Report generated."

      # Upload test report
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: dummytest-report
          path: Dummy.html
      - name: Confirm Report Upload
        run: "Test report uploaded successfully!"

