name: CI/CD Pipeline for API Tests

on:
  push:
    branches:
      - main  # Trigger when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger when a pull request is made to the main branch

jobs:
  test:
    runs-on: windows-latest  # Use a Windows environment for running the tests

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js (since Newman is a Node.js tool)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the version of Node.js you want 

      - name: Install dependency
        run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra


      # Run Postman tests using Newman
      - name: Run Postman tests using Newman
        run: |
          newman run "Practice for CICD.postman_collection.json"

      # Upload the test report
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: dummytest-report
          path: C:\Users\Administrator\Desktop\Anotherone\Dummy